const policyData = [
    {
        id: "a3B8k9Zc7D",
        policyNumber: "000001",
        insurancePackage: "基础保险",
        reimbursementAmount: 2000,
        illnessType: "癌症",
        reimbursementRatio: "80%",
        hospital: "成都中医药大学附属医院",
        doctor: "张文明",
        dateOfVisit: "2023-05-10",
        claimStatus: "待批准"
    },
    {
        id: "h7K2e4Ym9X",
        policyNumber: "000002",
        insurancePackage: "综合保险",
        reimbursementAmount: 1500,
        illnessType: "心脏病",
        reimbursementRatio: "90%",
        hospital: "四川大学华西医院",
        doctor: "李红梅",
        dateOfVisit: "2023-05-15",
        claimStatus: "待批准"
    },
    {
        id: "n5S9w6Rq3F",
        policyNumber: "000003",
        insurancePackage: "高端保险",
        reimbursementAmount: 1800,
        illnessType: "糖尿病",
        reimbursementRatio: "70%",
        hospital: "成都市第一人民医院",
        doctor: "王宇航",
        dateOfVisit: "2023-05-20",
        claimStatus: "已批准"
    },
    {
        id: "p2T4x7Vb9W",
        policyNumber: "000004",
        insurancePackage: "中级保险",
        reimbursementAmount: 2500,
        illnessType: "骨折",
        reimbursementRatio: "75%",
        hospital: "成都市第六人民医院",
        doctor: "刘婷",
        dateOfVisit: "2023-05-12",
        claimStatus: "待批准"
    },
    {
        id: "m8N1j3Lk6Q",
        policyNumber: "000005",
        insurancePackage: "综合保险",
        reimbursementAmount: 3000,
        illnessType: "中暑",
        reimbursementRatio: "85%",
        hospital: "成都市第三人民医院",
        doctor: "陈志强",
        dateOfVisit: "2023-05-18",
        claimStatus: "待批准"
    },
    {
        id: "d5F9r6Tq3G",
        policyNumber: "000006",
        insurancePackage: "基础保险",
        reimbursementAmount: 2200,
        illnessType: "感冒",
        reimbursementRatio: "80%",
        hospital: "解放军452医院",
        doctor: "赵丽",
        dateOfVisit: "2023-05-14",
        claimStatus: "已批准"
    },
    {
        id: "y2K4s8Xv7Z",
        policyNumber: "000007",
        insurancePackage: "高端保险",
        reimbursementAmount: 2800,
        illnessType: "哮喘",
        reimbursementRatio: "90%",
        hospital: "成都市第四人民医院",
        doctor: "孙明",
        dateOfVisit: "2023-05-21",
        claimStatus: "待批准"
    },
    {
        id: "b6D3c9Zx2F",
        policyNumber: "000008",
        insurancePackage: "中级保险",
        reimbursementAmount: 1900,
        illnessType: "胃炎",
        reimbursementRatio: "75%",
        hospital: "四川大学华西医院",
        doctor: "李小龙",
        dateOfVisit: "2023-05-11",
        claimStatus: "已批准"
    },
    {
        id: "k9V2x8Qz3B",
        policyNumber: "000009",
        insurancePackage: "基础保险",
        reimbursementAmount: 2100,
        illnessType: "头痛",
        reimbursementRatio: "80%",
        hospital: "成都市第三人民医院",
        doctor: "王芳",
        dateOfVisit: "2023-05-17",
        claimStatus: "已批准"
    },
    {
        id: "h5R8w9Pq7T",
        policyNumber: "000010",
        insurancePackage: "综合保险",
        reimbursementAmount: 3200,
        illnessType: "过敏",
        reimbursementRatio: "85%",
        hospital: "四川大学华西医院",
        doctor: "李平",
        dateOfVisit: "2023-05-23",
        claimStatus: "已批准"
    },
    {
        id: "s7Y6m8Nx1Z",
        policyNumber: "000011",
        insurancePackage: "高端保险",
        reimbursementAmount: 2400,
        illnessType: "痔疮",
        reimbursementRatio: "70%",
        hospital: "成都市第一人民医院",
        doctor: "王旭",
        dateOfVisit: "2023-05-13",
        claimStatus: "已批准"
    },
    {
        id: "g4J7f6Wp2D",
        policyNumber: "000012",
        insurancePackage: "基础保险",
        reimbursementAmount: 1800,
        illnessType: "腰痛",
        reimbursementRatio: "80%",
        hospital: "成都市第六人民医院",
        doctor: "刘明",
        dateOfVisit: "2023-05-16",
        claimStatus: "待批准"
    },
    {
        id: "q1Z3v7Mx8J",
        policyNumber: "000013",
        insurancePackage: "中级保险",
        reimbursementAmount: 2700,
        illnessType: "肺炎",
        reimbursementRatio: "75%",
        hospital: "成都市第三人民医院",
        doctor: "陈宇",
        dateOfVisit: "2023-05-19",
        claimStatus: "已批准"
    },
    {
        id: "e6T9r2Yq4F",
        policyNumber: "000014",
        insurancePackage: "综合保险",
        reimbursementAmount: 2100,
        illnessType: "感冒",
        reimbursementRatio: "85%",
        hospital: "成都市第一人民医院",
        doctor: "王文",
        dateOfVisit: "2023-05-22",
        claimStatus: "待批准"
    },
    {
        id: "w3X7v8Mq4Z",
        policyNumber: "000015",
        insurancePackage: "高端保险",
        reimbursementAmount: 2900,
        illnessType: "胃溃疡",
        reimbursementRatio: "90%",
        hospital: "解放军452医院",
        doctor: "赵伟",
        dateOfVisit: "2023-05-12",
        claimStatus: "已批准"
    },
    {
        id: "u5B9s3Fk7N",
        policyNumber: "000016",
        insurancePackage: "中级保险",
        reimbursementAmount: 2300,
        illnessType: "高血压",
        reimbursementRatio: "75%",
        hospital: "成都中医药大学附属医院",
        doctor: "陈林",
        dateOfVisit: "2023-05-15",
        claimStatus: "已批准"
    },
    {
        id: "r8P3z2Jv6X",
        policyNumber: "000017",
        insurancePackage: "基础保险",
        reimbursementAmount: 2400,
        illnessType: "糖尿病",
        reimbursementRatio: "80%",
        hospital: "四川大学华西医院",
        doctor: "李晓",
        dateOfVisit: "2023-05-20",
        claimStatus: "已批准"
    },
    {
        id: "t4W2q5Kv7B",
        policyNumber: "000018",
        insurancePackage: "综合保险",
        reimbursementAmount: 1800,
        illnessType: "感冒",
        reimbursementRatio: "85%",
        hospital: "成都市第三人民医院",
        doctor: "陈云",
        dateOfVisit: "2023-05-10",
        claimStatus: "已批准"
    },
    {
        id: "i6V8x7Tz3J",
        policyNumber: "000019",
        insurancePackage: "高端保险",
        reimbursementAmount: 2700,
        illnessType: "过敏",
        reimbursementRatio: "70%",
        hospital: "成都市第一人民医院",
        doctor: "王平",
        dateOfVisit: "2023-05-14",
        claimStatus: "待批准"
    },
    {
        id: "o9D1g5Hw6C",
        policyNumber: "000020",
        insurancePackage: "中级保险",
        reimbursementAmount: 3000,
        illnessType: "胃炎",
        reimbursementRatio: "75%",
        hospital: "成都中医药大学附属医院",
        doctor: "张华",
        dateOfVisit: "2023-05-18",
        claimStatus: "待批准"
    },
    {
        id: "f7R2j9Ew3Z",
        policyNumber: "000021",
        insurancePackage: "基础保险",
        reimbursementAmount: 2200,
        illnessType: "头痛",
        reimbursementRatio: "80%",
        hospital: "四川大学华西医院",
        doctor: "李玉",
        dateOfVisit: "2023-05-11",
        claimStatus: "已批准"
    },
    {
        id: "y5X4b8Pq9V",
        policyNumber: "000022",
        insurancePackage: "综合保险",
        reimbursementAmount: 2500,
        illnessType: "中暑",
        reimbursementRatio: "85%",
        hospital: "成都市第三人民医院",
        doctor: "陈明",
        dateOfVisit: "2023-05-17",
        claimStatus: "已批准"
    },
    {
        id: "x8Z3m2Np1T",
        policyNumber: "000023",
        insurancePackage: "高端保险",
        reimbursementAmount: 1900,
        illnessType: "骨折",
        reimbursementRatio: "70%",
        hospital: "成都市第六人民医院",
        doctor: "刘伟",
        dateOfVisit: "2023-05-13",
        claimStatus: "已批准"
    },
    {
        id: "l4K6f9Sv2W",
        policyNumber: "000024",
        insurancePackage: "基础保险",
        reimbursementAmount: 3200,
        illnessType: "癌症",
        reimbursementRatio: "75%",
        hospital: "四川大学华西医院",
        doctor: "李晶",
        dateOfVisit: "2023-05-16",
        claimStatus: "待批准"
    },
    {
        id: "a9Z6c8Vx3S",
        policyNumber: "000025",
        insurancePackage: "中级保险",
        reimbursementAmount: 1800,
        illnessType: "感冒",
        reimbursementRatio: "80%",
        hospital: "成都市第一人民医院",
        doctor: "王斌",
        dateOfVisit: "2023-05-19",
        claimStatus: "已批准"
    },
    {
        id: "v2B5j7Nk8Q",
        policyNumber: "000026",
        insurancePackage: "综合保险",
        reimbursementAmount: 2800,
        illnessType: "哮喘",
        reimbursementRatio: "90%",
        hospital: "解放军452医院",
        doctor: "赵雪",
        dateOfVisit: "2023-05-22",
        claimStatus: "待批准"
    },
    {
        id: "m6G8h4Rq3F",
        policyNumber: "000027",
        insurancePackage: "高端保险",
        reimbursementAmount: 2100,
        illnessType: "胃溃疡",
        reimbursementRatio: "85%",
        hospital: "成都市第一人民医院",
        doctor: "王峰",
        dateOfVisit: "2023-05-12",
        claimStatus: "已批准"
    },
    {
        id: "c5D9z8Vb2W",
        policyNumber: "000028",
        insurancePackage: "中级保险",
        reimbursementAmount: 2300,
        illnessType: "高血压",
        reimbursementRatio: "75%",
        hospital: "四川大学华西医院",
        doctor: "李林",
        dateOfVisit: "2023-05-15",
        claimStatus: "已批准"
    },
    {
        id: "e9J3v7Nx5K",
        policyNumber: "000029",
        insurancePackage: "基础保险",
        reimbursementAmount: 2400,
        illnessType: "糖尿病",
        reimbursementRatio: "80%",
        hospital: "成都市第三人民医院",
        doctor: "陈斌",
        dateOfVisit: "2023-05-20",
        claimStatus: "已批准"
    },
    {
        id: "g6T2j7Rw4B",
        policyNumber: "000030",
        insurancePackage: "综合保险",
        reimbursementAmount: 1800,
        illnessType: "感冒",
        reimbursementRatio: "85%",
        hospital: "成都市第六人民医院",
        doctor: "刘云",
        dateOfVisit: "2023-05-10",
        claimStatus: "已批准"
    },
    {
        id: "s8P4z2Jx7V",
        policyNumber: "000031",
        insurancePackage: "高端保险",
        reimbursementAmount: 2700,
        illnessType: "过敏",
        reimbursementRatio: "70%",
        hospital: "成都市第一人民医院",
        doctor: "王明",
        dateOfVisit: "2023-05-14",
        claimStatus: "待批准"
    },
    {
        id: "n6H5g9Rd2T",
        policyNumber: "000032",
        insurancePackage: "中级保险",
        reimbursementAmount: 3000,
        illnessType: "胃炎",
        reimbursementRatio: "75%",
        hospital: "成都中医药大学附属医院",
        doctor: "张云",
        dateOfVisit: "2023-05-18",
        claimStatus: "待批准"
    },
    {
        id: "q9M3k7Dx6G",
        policyNumber: "000033",
        insurancePackage: "基础保险",
        reimbursementAmount: 2200,
        illnessType: "头痛",
        reimbursementRatio: "80%",
        hospital: "四川大学华西医院",
        doctor: "李琳",
        dateOfVisit: "2023-05-11",
        claimStatus: "已批准"
    },
    {
        id: "f3G6j5Mv9S",
        policyNumber: "000034",
        insurancePackage: "综合保险",
        reimbursementAmount: 2500,
        illnessType: "中暑",
        reimbursementRatio: "85%",
        hospital: "成都市第三人民医院",
        doctor: "陈建",
        dateOfVisit: "2023-05-17",
        claimStatus: "已批准"
    },
    {
        id: "t2X7q5Zv4W",
        policyNumber: "000035",
        insurancePackage: "高端保险",
        reimbursementAmount: 1900,
        illnessType: "骨折",
        reimbursementRatio: "70%",
        hospital: "成都市第六人民医院",
        doctor: "刘建",
        dateOfVisit: "2023-05-13",
        claimStatus: "已批准"
    },
    {
        id: "i7C9v5Kj8Q",
        policyNumber: "000036",
        insurancePackage: "基础保险",
        reimbursementAmount: 3200,
        illnessType: "癌症",
        reimbursementRatio: "75%",
        hospital: "四川大学华西医院",
        doctor: "李建",
        dateOfVisit: "2023-05-16",
        claimStatus: "待批准"
    },
    {
        id: "w6P4m3Zv2H",
        policyNumber: "000037",
        insurancePackage: "中级保险",
        reimbursementAmount: 1800,
        illnessType: "感冒",
        reimbursementRatio: "80%",
        hospital: "成都市第一人民医院",
        doctor: "王建",
        dateOfVisit: "2023-05-19",
        claimStatus: "已批准"
    },
    {
        id: "k3Y7n8Qx4V",
        policyNumber: "000038",
        insurancePackage: "综合保险",
        reimbursementAmount: 2800,
        illnessType: "哮喘",
        reimbursementRatio: "90%",
        hospital: "解放军452医院",
        doctor: "赵明",
        dateOfVisit: "2023-05-22",
        claimStatus: "待批准"
    },
    {
        id: "a8V5n2Km3G",
        policyNumber: "000039",
        insurancePackage: "高端保险",
        reimbursementAmount: 2100,
        illnessType: "胃溃疡",
        reimbursementRatio: "85%",
        hospital: "成都市第一人民医院",
        doctor: "王建国",
        dateOfVisit: "2023-05-12",
        claimStatus: "已批准"
    },
    {
        id: "v4W2g7Kt6F",
        policyNumber: "000040",
        insurancePackage: "中级保险",
        reimbursementAmount: 2300,
        illnessType: "高血压",
        reimbursementRatio: "75%",
        hospital: "四川大学华西医院",
        doctor: "李明华",
        dateOfVisit: "2023-05-15",
        claimStatus: "已批准"
    }
]

export  {
    policyData
} 